Repository OpenCollarTeam/OpenCollar, pull requests merged in 2019-12, with the labels that each got.

#275 Resolve #54
  src/collar/oc_anim.lsl
  src/collar/oc_auth.lsl
  src/collar/oc_rlvsys.lsl
  src/collar/oc_settings.lsl
Labels: Feature

#290 Fix load timing on login
  src/collar/oc_settings.lsl
  src/collar/oc_sys.lsl
Labels: Do Not Merge (yet)

#289 Add Timer to release the wearer when the captor left the region
  src/spares/Apps/oc_capture.lsl
Labels: Do Not Merge (yet), Waiting for reply
