Repository OpenCollarTeam/OpenCollar, pull requests merged in 2019-10, with the labels that each got.

#248 Add error messages to oc_meshlabel when not correctly set up.
  src/collar/oc_meshlabel.lsl
Labels: Feature, Fixed

#249 new resize function!
  src/collar/oc_resizer.lsl
Labels: Working On It

#250 Create oc_presets
  src/spares/oc_presets
Labels: Feature

#256 Cuffs: remove unused functions
  src/cuffs/Right wrist/occ_appearance_cuff.lsl
  src/cuffs/Right wrist/occ_collar_pose.lsl
  src/cuffs/Right wrist/occ_slave_chains.lsl
  src/cuffs/Right wrist/occ_sys.lsl
  src/cuffs/Right wrist/occ_timer_cuff.lsl
  src/cuffs/Slave cuffs/occ_slave_chains.lsl
  src/cuffs/Slave cuffs/occ_slave_cuff.lsl
Labels: Refactoring
