Repository OpenCollarTeam/OpenCollar, pull requests merged in 2024-09, with the labels that each got.

#1082 Change legacy permissions notification in oc_couples
  src/collar/oc_couples.lsl
Labels: Discussion wanted, 8.3

#1085 Update oc_rlvextension.lsl
  src/collar/oc_leash.lsl
  src/collar/oc_rlvextension.lsl
Labels: 8.3

#1081 oc timer 8.3beta2 fixes
  src/Apps/oc_timer.lsl
Labels: 8.3, Needs testing

#1086 Update Checkboxes throughout
  src/Apps/oc_OwnerOnlineCheck.lsl
  src/Apps/oc_capture.lsl
  src/Apps/oc_detach.lsl
  src/Apps/oc_outfits.lsl
  src/Apps/oc_spy.lsl
  src/Apps/oc_undress.lsl
  src/collar/oc_anim.lsl
  src/collar/oc_core.lsl
  src/collar/oc_label.lsl
  src/collar/oc_meshlabel.lsl
  src/collar/oc_relay.lsl
  src/collar/oc_rlvsuite.lsl
  src/collar/oc_settings.lsl
  src/collar/oc_titler.lsl
Labels: 8.3

#1097 Clear menus to invalidate auth when public mode is turned off
  src/collar/oc_dialog.lsl
Labels: 8.3, Needs testing

#1091 particle leashlength fix
  src/collar/oc_particle.lsl
Labels: 8.3, Ready to merge

#1096 OBJECT_TEMP_ATTACHED rejection in oc_API for interface channel
  src/collar/oc_api.lsl
Labels: 8.3

#1093 Nikki lacrima minorclean rlvsuite
  src/collar/oc_rlvsuite.lsl
Labels: 8.3
